/*
 * Selling Partner API for Finances
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazon.spapi.models.finances;

import java.util.Objects;
import java.util.Arrays;
import com.amazon.spapi.models.finances.Currency;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * A tax deduction at source (TDS) claim reimbursement event on the seller&#x27;s account.
 */
@Schema(description = "A tax deduction at source (TDS) claim reimbursement event on the seller's account.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-19T18:22:12.816507+08:00[Asia/Shanghai]")
public class TDSReimbursementEvent {
  @SerializedName("PostedDate")
  private OffsetDateTime postedDate = null;

  @SerializedName("TdsOrderId")
  private String tdsOrderId = null;

  @SerializedName("ReimbursedAmount")
  private Currency reimbursedAmount = null;

  public TDSReimbursementEvent postedDate(OffsetDateTime postedDate) {
    this.postedDate = postedDate;
    return this;
  }

   /**
   * Get postedDate
   * @return postedDate
  **/
  @Schema(description = "")
  public OffsetDateTime getPostedDate() {
    return postedDate;
  }

  public void setPostedDate(OffsetDateTime postedDate) {
    this.postedDate = postedDate;
  }

  public TDSReimbursementEvent tdsOrderId(String tdsOrderId) {
    this.tdsOrderId = tdsOrderId;
    return this;
  }

   /**
   * A tax deduction at source (TDS) claim identifier.
   * @return tdsOrderId
  **/
  @Schema(description = "A tax deduction at source (TDS) claim identifier.")
  public String getTdsOrderId() {
    return tdsOrderId;
  }

  public void setTdsOrderId(String tdsOrderId) {
    this.tdsOrderId = tdsOrderId;
  }

  public TDSReimbursementEvent reimbursedAmount(Currency reimbursedAmount) {
    this.reimbursedAmount = reimbursedAmount;
    return this;
  }

   /**
   * Get reimbursedAmount
   * @return reimbursedAmount
  **/
  @Schema(description = "")
  public Currency getReimbursedAmount() {
    return reimbursedAmount;
  }

  public void setReimbursedAmount(Currency reimbursedAmount) {
    this.reimbursedAmount = reimbursedAmount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TDSReimbursementEvent tdSReimbursementEvent = (TDSReimbursementEvent) o;
    return Objects.equals(this.postedDate, tdSReimbursementEvent.postedDate) &&
        Objects.equals(this.tdsOrderId, tdSReimbursementEvent.tdsOrderId) &&
        Objects.equals(this.reimbursedAmount, tdSReimbursementEvent.reimbursedAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(postedDate, tdsOrderId, reimbursedAmount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TDSReimbursementEvent {\n");

    sb.append("    postedDate: ").append(toIndentedString(postedDate)).append("\n");
    sb.append("    tdsOrderId: ").append(toIndentedString(tdsOrderId)).append("\n");
    sb.append("    reimbursedAmount: ").append(toIndentedString(reimbursedAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
