/*
 * Selling Partner API for Catalog Items
 * The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.  For more information, see the [Catalog Items API Use Case Guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/catalog-items-api-use-case-guide/catalog-items-api-use-case-guide_2020-12-01.md).
 *
 * OpenAPI spec version: 2020-12-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazon.spapi.model.catalogitems;

import java.util.Objects;
import java.util.Arrays;
import com.amazon.spapi.model.catalogitems.ItemSalesRank;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Sales ranks of an Amazon catalog item for the indicated Amazon marketplace.
 */
@Schema(description = "Sales ranks of an Amazon catalog item for the indicated Amazon marketplace.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-18T11:31:18.960277+08:00[Asia/Shanghai]")
public class ItemSalesRanksByMarketplace {
  @SerializedName("marketplaceId")
  private String marketplaceId = null;

  @SerializedName("ranks")
  private List<ItemSalesRank> ranks = new ArrayList<ItemSalesRank>();

  public ItemSalesRanksByMarketplace marketplaceId(String marketplaceId) {
    this.marketplaceId = marketplaceId;
    return this;
  }

   /**
   * Amazon marketplace identifier.
   * @return marketplaceId
  **/
  @Schema(required = true, description = "Amazon marketplace identifier.")
  public String getMarketplaceId() {
    return marketplaceId;
  }

  public void setMarketplaceId(String marketplaceId) {
    this.marketplaceId = marketplaceId;
  }

  public ItemSalesRanksByMarketplace ranks(List<ItemSalesRank> ranks) {
    this.ranks = ranks;
    return this;
  }

  public ItemSalesRanksByMarketplace addRanksItem(ItemSalesRank ranksItem) {
    this.ranks.add(ranksItem);
    return this;
  }

   /**
   * Sales ranks of an Amazon catalog item for an Amazon marketplace.
   * @return ranks
  **/
  @Schema(required = true, description = "Sales ranks of an Amazon catalog item for an Amazon marketplace.")
  public List<ItemSalesRank> getRanks() {
    return ranks;
  }

  public void setRanks(List<ItemSalesRank> ranks) {
    this.ranks = ranks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemSalesRanksByMarketplace itemSalesRanksByMarketplace = (ItemSalesRanksByMarketplace) o;
    return Objects.equals(this.marketplaceId, itemSalesRanksByMarketplace.marketplaceId) &&
        Objects.equals(this.ranks, itemSalesRanksByMarketplace.ranks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(marketplaceId, ranks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemSalesRanksByMarketplace {\n");
    
    sb.append("    marketplaceId: ").append(toIndentedString(marketplaceId)).append("\n");
    sb.append("    ranks: ").append(toIndentedString(ranks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
